
name: Lint and test

on:
  push:
    branches: ['main']

jobs:
  lint-and-test:
    runs-on: golang:1.19

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: go get .
      - name: Lint
        run: test -z $(gofmt -e -l cmd/ internal/)
      - name: Test
        run: go test ./...
